<a href="https://colab.research.google.com/github/GoldenWind8/AlgorithmicTrading/blob/master/NeuralNetworkColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import  tensorflow  as  tf
import pandas as pd

In [2]:
import pandas as pd
from datetime import datetime, timedelta
class DataHandler:
    def __init__(self, file_path):
        self.file_path = file_path

    def read_data(self):
        # read the data from the CSV file into a DataFrame
        df = pd.read_csv(self.file_path)
        return df

    def format_tickstory_data(self, df):
        # parse the date and timestamp strings into datetime objects
        df['DateTime'] = pd.to_datetime(df['Date'].astype(str) + ' ' + df['Timestamp'])

        # create a reference datetime to determine the amount of seconds passed.
        reference = datetime(2022, 11, 29)

        # subtract the reference datetime from the DateTime column
        timedelta = df['DateTime'] - reference

        # convert the timedelta to seconds
        seconds = timedelta.dt.total_seconds()

        # add the seconds to the DataFrame
        df['Seconds'] = seconds

        #Drop NaN values
        df = df.dropna()

        return df

In [5]:
#use datahandler to read in csv file
dataHandler = DataHandler('Data/EURCAD.csv')
data = dataHandler.read_data()

data = dataHandler.format_tickstory_data(data)
data.head()

,Date,Timestamp,Open,High,Low,Close,Volume,DateTime,Seconds
0,20221129,00:00:00,1.39524,1.39531,1.39521,1.39531,61.859999,2022-11-29 00:00:00,0.0
1,20221129,00:00:10,1.39531,1.39533,1.39529,1.39529,31.319999,2022-11-29 00:00:10,10.0
2,20221129,00:00:20,1.39529,1.39531,1.39526,1.39531,24.240000,2022-11-29 00:00:20,20.0
3,20221129,00:00:30,1.39528,1.39532,1.39528,1.39532,12.840000,2022-11-29 00:00:30,30.0
4,20221129,00:00:40,1.39532,1.39534,1.39526,1.39531,48.139999,2022-11-29 00:00:40,40.0

In [10]:
def deepLearningModel(data_frame):
    # Split the data into training and testing sets
    train_data = data_frame.iloc[:int(len(data) * 0.8)]
    test_data = data_frame.iloc[int(len(data) * 0.8):]

    # Define the model architecture
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(32, input_shape=(1,), activation='relu'))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Train the model
    history = model.fit(train_data['Seconds'], train_data['Close'], epochs=50,
                        validation_data=(test_data['Seconds'], test_data['Close']))

    # Evaluate the model
    test_loss, test_acc = model.evaluate(test_data['Seconds'], test_data['Close'])
    print('Test loss:', test_loss)
    print('Test accuracy:', test_acc)

    # Make predictions
    predictions = model.predict(test_data['Seconds'])

In [ ]:
deepLearningModel(data)

Epoch 1/50
2722/2722 [==============================] - 7s 2ms/step - loss: -13248767.0000 - accuracy: 0.0000e+00 - val_loss: -92300288.0000 - val_accuracy: 0.0000e+00
Epoch 2/50
2722/2722 [==============================] - 6s 2ms/step - loss: -80740552.0000 - accuracy: 0.0000e+00 - val_loss: -315797696.0000 - val_accuracy: 0.0000e+00
Epoch 3/50
2722/2722 [==============================] - 6s 2ms/step - loss: -194436816.0000 - accuracy: 0.0000e+00 - val_loss: -640201472.0000 - val_accuracy: 0.0000e+00
Epoch 4/50
2722/2722 [==============================] - 6s 2ms/step - loss: -348675392.0000 - accuracy: 0.0000e+00 - val_loss: -1060803584.0000 - val_accuracy: 0.0000e+00
Epoch 5/50
2722/2722 [==============================] - 6s 2ms/step - loss: -542028736.0000 - accuracy: 0.0000e+00 - val_loss: -1575057792.0000 - val_accuracy: 0.0000e+00
Epoch 6/50
2722/2722 [==============================] - 6s 2ms/step - loss: -773974528.0000 - accuracy: 0.0000e+00 - val_loss: -2182236160.0000 - val_accuracy: 0.0000e+00
Epoch 7/50
2722/2722 [==============================] - 5s 2ms/step - loss: -1044433920.0000 - accuracy: 0.0000e+00 - val_loss: -2881744896.0000 - val_accuracy: 0.0000e+00
Epoch 8/50
2722/2722 [==============================] - 6s 2ms/step - loss: -1352721408.0000 - accuracy: 0.0000e+00 - val_loss: -3672870400.0000 - val_accuracy: 0.0000e+00
Epoch 9/50
2722/2722 [==============================] - 6s 2ms/step - loss: -1699049472.0000 - accuracy: 0.0000e+00 - val_loss: -4555412992.0000 - val_accuracy: 0.0000e+00
Epoch 10/50
2722/2722 [==============================] - 6s 2ms/step - loss: -2083083008.0000 - accuracy: 0.0000e+00 - val_loss: -5528817664.0000 - val_accuracy: 0.0000e+00
Epoch 11/50
2722/2722 [==============================] - 5s 2ms/step - loss: -2504250624.0000 - accuracy: 0.0000e+00 - val_loss: -6592017408.0000 - val_accuracy: 0.0000e+00
Epoch 12/50
2722/2722 [==============================] - 7s 2ms/step - loss: -2962751488.0000 - accuracy: 0.0000e+00 - val_loss: -7745880576.0000 - val_accuracy: 0.0000e+00
Epoch 13/50
2722/2722 [==============================] - 6s 2ms/step - loss: -3459159808.0000 - accuracy: 0.0000e+00 - val_loss: -8990279680.0000 - val_accuracy: 0.0000e+00
Epoch 14/50
2722/2722 [==============================] - 6s 2ms/step - loss: -3992498176.0000 - accuracy: 0.0000e+00 - val_loss: -10323831808.0000 - val_accuracy: 0.0000e+00
Epoch 15/50
2643/2722 [============================>.] - ETA: 0s - loss: -4556931584.0000 - accuracy: 0.0000e+00